[package]
name = "rutas_autobuses"
version = "0.1.3"
edition = "2021"

[lib]
name = "buscador_rutas"
path = "src/ruta.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.*", features = ["serde"] }
